### ISSUE TITLE
About the version of Python, TensorFlow, Keras

### ISSUE THREAD

**Issue by jchuanHou** [AbiXnash/An-Intrusion-Detection-System-using-Deep-Learning-models-on-UNSW_NB15dataset#1]
Hello! Your work is great! Could you please provide the version of Python, TensorFlow, Keras and so on? Thank you !!!

**Comment by AbiXnash** [comment]
Hi! Thanks for your interest in my research. Currently, I haven't provided a standalone Python (.py) version of the code. However, you can download the Jupyter Notebook file (.ipynb) from the repository and convert it into Python code if needed. This can easily be done by running:

```bash
jupyter nbconvert --to script your_notebook.ipynb
